server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.0.193:3306/cloud_order?useSSL=false
    username: root
    password: CSK1234csk
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka